### ISSUE TITLE
Improve updater error messages

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#152]
It is sometimes hard to understand why the validation failed:
- the authentication repository is almost up to date (one commit missing)
- some target repositories were manually cloned and the default branch was checked out
- the target files corresponding to the manually cloned target repositories were not updated in the last (missing) commit

Seemingly, everything is valid. However, we cannot simply checkout the branch specified in the newest target file and then validate the repository. If the local repository does not exist, it might not have been validated and the updater needs to check all of its commits. This results in a mismatch between auth repo's commit and target commits.

Second problem:
- Some commits were not pushed and the last validated commit was updated manually, so that the error that the topic commit and last validated commit are not identical does not occur
- Last validated commit is added to the list of commits to be validated during this update
- Remote repository is cloned and the update process fails because this last validated commit is not in the remote repository
- The error message say that metadata cannot be loaded

It's fine that the update is failing, but this is something we might try to do while testing other parts of the system and it's hard to figure out what we've done wrong

Difficult to figure out why a mismatch happened if there are more target commits than new commit and all existing commits match:

```
(Pdb) new_commits
['8f785fcb6bff10eeef02ed7081560230d73e15cd']
(Pdb) target_commits
['8f785fcb6bff10eeef02ed7081560230d73e15cd', '48e5e2f2bef5413334f408b5c52cdb1b75c2a36a', '8fe71b66505e80870253480da48f73d1b19611da', '5fbbe7a3503afadad1bc77ce8838638bfc454451', '0f0735b314834ad2ea6b42ab8a984d1bc2391cf4', 'f0e86d8e3193846c823e97bfd46d36161b952b8c', '320f1199804175b8061fe2a8fb1ac525bc6b41a7', 'e66df0093c031607a02ccd395ad321429f068d07', 'd1c1e3ff35e5ff75ba21e531b62a047dc447b65d']
```

**Comment by n-dusan** [comment]
from @dgreisen:
taf validation error messages needs a lot more info. something like: "failure to validate cityofsanameteo/law commit abc123 committed on yyyy-mm-dd: data repository cityofsanmateo/law-xml was supposed to be at commit def456 and but repo was at abc789"
