### ISSUE TITLE
Add support for specifying default branch of a repository when calling the updater of automatically determining it

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#169]
With GitHub transitioning to "main" branches, some repositories will have a master branch, others will have a master branch.

**Comment by renatav** [comment]
@n-dusan Do you think there is still need to support specification of the default branch when calling the updater, or will it always be correctly detected?

**Comment by n-dusan** [comment]
I don't know, but I haven't used default branch from CLI in a while now. Maybe the right call is to add tests that demonstrate that default branch detection works and then remove the default branch from CLI?
