### ISSUE TITLE
Check if `version` number in metadata is consistent 

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#199]
We shouldn't allow someone to force push and revert to 1 commit, while for example keeping `version` metadata value to `13`

**Comment by renatav** [comment]
@n-dusan Any chance you remember more details about this issue? If you force push and remove commits, the metadata version will not remain the same. Was it related to the updater or our branch validation?

**Comment by renatav** [comment]
I am not quite sure why we opened this issue, but the TUF updater will fail if version is manually set, without the signature calculated again. This could be related to #385. I'll close this issue
