### ISSUE TITLE
All fetched commits fails if there is no working tree

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#233]
If there is no working tree and the repository is completely empty with no commits, [fetched_commits](https://github.com/openlawlibrary/taf/blob/master/taf/updater/updater.py#L1010) fails and prints: 
`rev-parse --abbrev-ref HEAD:
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions`

**Comment by n-dusan** [comment]
`all_commits_since_commit` raises error after https://github.com/openlawlibrary/taf/pull/278 gets merged

**Comment by renatav** [comment]
Create a test first. We might have already fixed this, it's difficult to check.
