### ISSUE TITLE
Invalid fix for pytest11 entry_point hook

### ISSUE THREAD

**Issue by igordejanovic** [openlawlibrary/taf#288]
Fix in #200 seems incomplete. [This line](https://github.com/openlawlibrary/taf/commit/85512c9c14d5ffcf87146adb4dd43eaf937f1cf0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L80) should be removed. 

I found out this by coincidence involving several problems:
- wheels on PyPI have `taf.tests`  (but shouldn't)
- Source distribution on PyPI doesn't have `taf.tests` (but probably should?)
- There are only wheels for win and macos but not for linux so on my machine source distribution is pulled in by pip so I have no `taf.tests` in my environment. Thus calling pytest on anything breaks.

**Comment by renatav** [comment]
Fixed by merging  #301
