### ISSUE TITLE
Load only latest `mirrors.json`

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#332]
Running taf repo update on a repository with historical mirrors.json might be incorrect, if mirrors.json got updated in the meantime. Result is that the wrong remote could be set to the repository, and other validation fails with:

`taf.exceptions.UpdateFailedError: Update of repository/law failed due to error 'NoneType' object has no attribute 'target'`

**Comment by renatav** [comment]
I am not sure that this error was caused by only `mirrors.json` update. If names of repositories stay the same, the repositories that are loaded at the end will have the newest urls. Any idea how to reproduce the issue?

**Comment by renatav** [comment]
The underlying issue was that the repository which is causing the issue was removed before `mirrors.json` was fixed. I think it makes more sense to figure out if we want to only load repositories from the newest `repositories.json`

**Comment by renatav** [comment]
Closing since the issue was caused by the way repositories are loaded.
