### ISSUE TITLE
Ergonomics

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#336]
We need to make adding repositories, dependencies and roles to the law repository simple and robust. Here is a rough first outline of ideas. List will get updated/modified when necessary:

- Introduce git hooks to check if local repository is synced with remote.
- End-user should not need to update snapshot/timestamp. Snapshot and timestamp keys should live on CI. 
- Adding repositories, dependencies and roles is done by creating an update branch, which gets merged by the server into the main branch. The update to repositories/dependencies should not complete until the server agrees. Server will agree when the update branch is valid/able to get merged into main branch.

Related issues:
- [x] openlawlibrary/taf#210 
- [x] openlawlibrary/taf#335 
- [x] openlawlibrary/taf#333 
- [x] openlawlibrary/stelae#28

**Comment by renatav** [comment]
There is a new issue for the creation of update branches (#498) and all other tasks are done. Closing this issue
