### ISSUE TITLE
Rework updater testing framework

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#383]
At the moment, for each test we have a set of git repositories which were set up manually and committed after renaming the `.git` folders to `git`. Given the tools that were developed after initial this testing framework was set up, it should be possible to recreate all of the repositories and the appropriate states they are programmatically. This should make it possible to add new tests with much less effort.

List of tests that we need to add:
- Execution of scripts
- Update of repositories which reference other repositories (which contain `dependenceis.json`)
- Add tests for more states in which authentication and target repositories can be in when the updater is called. See issue #210 
which lists a number of different states the repositories can be in.
- Add tests for invalid metadata - `root`, `targets`, `snapshot`, `timestamp`

We also need to add tests which would include authentication repositories which contain dependencies and scripts.

**Comment by renatav** [comment]
Initial work on setting up repositories programmatically and updating repositories which contain `dependencies.json` done in #386

**Comment by n-dusan** [comment]
Add unit tests to taf, break down taf code into pure functions that are easily testable.
