### ISSUE TITLE
Add `taf roles list` command

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#400]
A command that lists all roles in an authentication repository.

`> taf roles list`

Output:

- root (threshhold: 2)
  - target (threshhold: 1)
    - law
    - ...
  - timestamp
  - ...

(child roles can only be delegated by a threshhold of parent role keys)

**Comment by renatav** [comment]
This should be easy to do. There is `get_all_roles` in `repository_tool` - can be called on any `AuthenticationRepository's` instance. To get a threshold, there is `auth_repo.get_role_threshold(role)`. For each role, there is `find_delegated_roles_parent` which can find the name of the parent role.
