### ISSUE TITLE
Profile updater

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#407]
Updater's performance is the biggest issue right now

**Comment by ronantakizawa** [comment]
The slow performance is coming from functions clone_remote_and_run_tuf_updater and clone_or_fetch_users_auth_repo in updater_pipeline.py, both are either cloning or fetching. 
<img width="1409" alt="Screenshot 2024-05-21 at 6 24 32 PM" src="https://github.com/openlawlibrary/taf/assets/71115970/bade845d-5320-41ac-876f-76e1c5684ad0">
![output](https://github.com/openlawlibrary/taf/assets/71115970/e99f77bc-3522-427f-84e7-4cc63563573d)
