### ISSUE TITLE
Require target-name parameter 

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#430]
`taf targets add-repo --target-name` parameter should be a required path argument

**Comment by Rana-KV** [comment]
Hi @renatav, I would like take up this issue and work on it.

**Comment by renatav** [comment]
@Rana-KV Awesome, I assigned it to you,

**Comment by Rana-KV** [comment]
Thanks for assigning the issues @renatav
I have question regarding the changes. If target-name is required, then can I remove the fallback option to use target-path?

![TAF-Capture](https://github.com/openlawlibrary/taf/assets/19876949/f04ab22f-fcd8-404e-a816-caf87593b403)

**Comment by renatav** [comment]
@Rana-KV We tend to follow a certain convention regarding where the repositories are located. Their filesystem paths tend to include their names. This will be the case if you use the updater to clone the repositories, like it is intended. So, if you have a name, the chances are that we can also correctly calculate the path. If for whatever reason that is not the case, we probably should still make it possible to specify a different path. So, let's actually reverse the order of this `if` and `elif` instead of removing the `elif`

**Comment by Rana-KV** [comment]
Thanks for the information @renatav, I have reversed the order and still kept the description in targest.py about target-name parameter as optional because it be still done with just taget-path.
