### ISSUE TITLE
opt-out god of wisdom / wealth

### ISSUE THREAD

**Issue by kingkong2024** [openlawlibrary/taf#451]
https://github.com/openlawlibrary/taf/issues/397#issue-2186347331

**Comment by kingkong2024** [comment]
Council of the District of Columbia logo
D.C. Law Library


Advanced search help
Toggle mobile menu
NAVIGATION
[D.C. Law Library](https://code.dccouncil.gov/)
[Federal Laws Codified in the D.C. Code](https://code.dccouncil.gov/fedlaws)
[The 89th Congress](https://code.dccouncil.gov/fedlaws/89)
Pub. L. 89-554. An Act to enact title 5, United States Code, ""Government Organization and Employees"" codifying the general and permanent laws relating to the organization of the Government of the United States and to its civilian officers and employees.
Pub. L. 89-554. An Act to enact title 5, United States Code, ""Government Organization and Employees"" codifying the general and permanent laws relating to the organization of the Government of the United States and to its civilian officers and employees.

[HTML Unavailable ([PDF](https://www.gpo.gov/fdsys/pkg/STATUTE-80/pdf/STATUTE-80-Pg378.pdf))]

LAW INFORMATION
Cites
Pub. L. 89-55480 Stat. 378 ([PDF](https://www.gpo.gov/fdsys/pkg/STATUTE-80/pdf/STATUTE-80-Pg378.pdf))
Effective
Sept. 6, 1966
We cannot respond to questions regarding the law.
Council of the District of Columbia logo
The codes and laws on this website are in the public domain.
Please do not scrape. Instead, bulk download the [HTML](https://github.com/dccouncil/law-html) or [XML](https://github.com/dccouncil/law-xml).
Powered by the non-profit [Open Law Library](http://www.openlawlib.org/)
Council of the District of Columbia logo
D.C. Law Library



Advanced search help
Toggle mobile menu
NAVIGATION
[D.C. Law Library](https://code.dccouncil.gov/)
D.C. Laws Codified in the D.C. Code
D.C. Laws Codified in the D.C. Code

For laws not codified in the D.C. Code, please visit [LIMS](http://lims.dccouncil.us/).
[Council Period 25 (2023-2024)](https://code.dccouncil.gov/dclaws/25)
327 documents
[Council Period 24 (2021-2022)](https://code.dccouncil.gov/dclaws/24)
620 documents
[Council Period 23 (2019-2020)](https://code.dccouncil.gov/dclaws/23)
453 documents
[Council Period 22 (2017-2018)](https://code.dccouncil.gov/dclaws/22)
439 documents
[Council Period 21 (2015-2016) ](https://code.dccouncil.gov/dclaws/21)
344 documents
[Council Period 20](https://code.dccouncil.gov/dclaws/20)
160 documents
[Council Period 19](https://code.dccouncil.gov/dclaws/19)
179 documents
[Council Period 18](https://code.dccouncil.gov/dclaws/18)
195 documents
[Council Period 17](https://code.dccouncil.gov/dclaws/17)
198 documents
[Council Period 16](https://code.dccouncil.gov/dclaws/16)
171 documents
[Council Period 15](https://code.dccouncil.gov/dclaws/15)
184 documents
[Council Period 14](https://code.dccouncil.gov/dclaws/14)
146 documents
[Council Period 13](https://code.dccouncil.gov/dclaws/13)
171 documents
[Council Period 12](https://code.dccouncil.gov/dclaws/12)
173 documents
[Council Period 11](https://code.dccouncil.gov/dclaws/11)
153 documents
[Council Period 10](https://code.dccouncil.gov/dclaws/10)
153 documents
[Council Period 9](https://code.dccouncil.gov/dclaws/9)
162 documents
[Council Period 8](https://code.dccouncil.gov/dclaws/8)
165 documents
[Council Period 7](https://code.dccouncil.gov/dclaws/7)
145 documents
[Council Period 6](https://code.dccouncil.gov/dclaws/6)
134 documents
[Council Period 5](https://code.dccouncil.gov/dclaws/5)
121 documents
[Council Period 4](https://code.dccouncil.gov/dclaws/4)
138 documents
[Council Period 3](https://code.dccouncil.gov/dclaws/3)
96 documents
[Council Period 2](https://code.dccouncil.gov/dclaws/2)
95 documents
[Council Period 1](https://code.dccouncil.gov/dclaws/1)
93 documents
[Legislative Assembly](https://code.dccouncil.gov/dclaws/legAssem)
5 documents
[R.S., D.C.. Revised Statutes of the District of Columbia.](https://code.dccouncil.gov/dc/council/revised-statutes.html)
We cannot respond to questions regarding the law.
Council of the District of Columbia logo
The codes and laws on this website are in the public domain.
Please do not scrape. Instead, bulk download the [HTML](https://github.com/dccouncil/law-html) or [XML](https://github.com/dccouncil/law-xml).
Powered by the non-profit [Open Law Library](http://www.openlawlib.org/).

**Comment by renatav** [comment]
If there is an issue with the DC site, please use the contact listed there to report the issue.
