### ISSUE TITLE
More user-friendly option to specify keys when using multiple yubikeys

### ISSUE THREAD

**Issue by ronantakizawa** [openlawlibrary/taf#509]
Currently (Since PR #503), Yubikeys are specified via their serial number when multiple Yubikeys are used, but this is not an optimal solution.

**Comment by n-dusan** [comment]
Prerequisite to this issue is https://github.com/openlawlibrary/taf/pull/512 resolved

**Comment by renatav** [comment]
I am going to close this and update the using multiple yubikeys issue, since the plan now is to revisit this feature after the update to the new version of TUF pr is merged.
