### ISSUE TITLE
If top-level auth repo is unchanged, `taf repo update` doesn't update dependencies

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#520]
Taf repo update needs to update dependent auth repos, even if top level did not change

**Comment by renatav** [comment]
This was not a design decision, the dependencies are supposed to be updated even if the parent repo was not updated, as long as it's update didn't fail (even if the update was partial). I haven't really thought about what should happen in case of a partial update, although that is not related to this issues. This is what this code looks like: https://github.com/openlawlibrary/taf/blob/5e54b8e07b411b00d055766585e063de29b896b2/taf/updater/updater.py#L451

So, if the updater is skipping the update of these child repositories, it means that either there is something wrong with the --no-deps flag, or th update data is not getting set properly.
I think that this would be a good issue for someone learning the updater to tackle. If there is no such person and this needs to be resolved asap, I'll look into it

**Comment by renatav** [comment]
Resolved by merging #528
