### ISSUE TITLE
Update of 'repository' failed due to error: 'NoneType' object has no attribute 'urls' when auth repository has dependencies

### ISSUE THREAD

**Issue by n-dusan** [openlawlibrary/taf#522]
Steps to reproduce the issue:

- [ ] In the archive directory, run `taf repo clone git@github.com:openlawlibrary/open-law.git --path ./openlawlibrary/open-law`
- [ ] `cd openlawlibrary/_open-law`
- [ ] `rm last_validated_commit`
- [ ] cd ../open-law
- [ ] `taf repo update`

The issue is [here](https://github.com/openlawlibrary/taf/blob/5e54b8e07b411b00d055766585e063de29b896b2/taf/updater/updater.py#L484), because the [outputs](https://github.com/openlawlibrary/taf/blob/5e54b8e07b411b00d055766585e063de29b896b2/taf/updater/updater.py#L465) has `None` values for all dependencies.

**Comment by renatav** [comment]
This error suggests that there is a problem with instantiating dependencies. Looks like it will be simple to add a test. There are tests for update with dependencies, so just delete th last validated commit in that setup
