### ISSUE TITLE
Add signing keys given a public key when creating a new authentication repository

### ISSUE THREAD

**Issue by renatav** [openlawlibrary/taf#93]
When creating a new authentication repository we should be able to add signing keys by providing public keys exported from yubikeys

**Comment by renatav** [comment]
I'm trying to brainstorm on how to define keys when defining that new repository description file. Based on TUF's specifications and some discussions we had earlier, this is my initial draft:
```
{
  "keys": {
    "user1": {
      "public": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtdvJF1Q7fRNTQfgGMH/W\n2Sb4O/PemLHKcBj6Q1Nadvii+lF+lfsD/VqzEuNaM2fpJpostWzJR1jdeyjRZS9G\ndToEA9iSD0MczHRLWa9a1NMcPBC/Edts1oXogk23+NSL/Ugc5H+WikDuwMMYhA3o\nNgVgAtfDfJQJFkbI033DwcYjbBmlt/gnTVNUSHuoG8M2EurchMnZZIqSawEaL82Q\nIFUhEuGSljcb/WRj6XHY7upCvjJOMN2kH/zz4kGR8j5t61TKiLiepjunuQMGg+fl\njEm4v0fandpwWLdx7kYSbftmbQjnuPhBd3g3BQ721O4dYkLA/ncca9XryLqN8Cac\ngQIDAQAB\n-----END PUBLIC KEY-----",
      "scheme": "rsa-pkcs1v15-sha256"
    },
    "user2": {
      "public": "-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA95lvROpv0cjcXM4xBYe1\nhNYajb/lfM+57UhTteJsTsUgFefLKJmvXLZ7gFVroHTRzMeU0UvCaEWAxFWJiPOr\nxYBOtClSiPs4e0a/safLKDX0zBwT776CqA/EJ/P6+rPc2E2fawmq1k8RzalJj+0W\nz/xr9fKyMpZU7RQjJmuLcyqfUYTdnZHADn0CDM54gBZ4dYDGGQ70Pjmc1otq4jzh\nI390O4W9Gj9yXd6SyxW2Wpj2CI3g4J0pLl2c2Wjf7Jd4PVNxLGAFOU2YLoI4F3Ri\nsACFUWjfT7p6AagSPStzIMik1YfLq+qFUlhn3KbNMAY9afkvdbTPWT+vajjsoc4c\nOAex1y/uZ2npn/5Q0lT7gMH/JxB3GmAYHCew5W6GmO2mRfNO3J8A+hqS3nKGEbfR\ncb7V176O/tdRM0HguIWAuV75khrCpGLx/fZNAMFf3Q9p0iJsx9p6gCAHERi5e4BJ\nSCBkbtVGGsQ7JM7ptSiLLgi79hIXWehZFUIjuU7a2y4xAgMBAAE=\n-----END PUBLIC KEY-----",
      "scheme": "rsa-pkcs1v15-sha256"
    },
    "userYK": {
      "yubikey": true
    },
    "snapshot1": {
      "keystore" : true,
      "length": 3072,
      "scheme": "rsa-pkcs1v15-sha256"
    },
    "snapshot2": {
      "keystore" : true,
      "length": 3072,
      "scheme": "rsa-pkcs1v15-sha256"
    },
    "timestamp": {
      "keystore": true,
      "length": 3072,
      "scheme": "rsa-pkcs1v15-sha256"
    }
  },
  "roles": {
      "root": {
        "number": 2,
        "threshold": 1,
        "keyids": [
          "user1", "user2"
        ]
      },
      "targets": {
        "number": 2,
        "threshold": 1,
        "keyids": [
          "user1", "user2"
        ],
        "delegations": {
          "roles": {
            "law": {
              "paths": [
                "cityofsanmateo/law-xml",
                "cityofsanmateo/law-html",
                "cityofsanmateo/law-xml-codified",
                "capstone",
                "branch",
                "law/capstone",
                "law/branch"
                ],
              "number": 3,
              "threshold": 1,
              "terminating": true,
              "keyids": [
                "user1", "user2", "userYK"
              ]
            }
          }
        }
      },
      "snapshot": {
        "number": 2,
        "threshold": 1,
        "keyids": [
          "snapshot1", "snapshot2"
        ]
      },
      "timestamp": {
        "number": 1,
        "threshold": 1,
        "keyids": [
          "timestamp"
        ]
      }
    },
  "keystore": "test/keystore"
}
```

The idea is to be able to name the keys however we want (as long as the names are unique). TUF calculates an id based on the the public key, while here we can specify the name ourselves

**Comment by dgreisen** [comment]
Regarding last question:

What if we basically made it possible to "sync" the keys from one repo to another? So, e.g., I remove Jason's key and add Tom's key to `openlawlibrary/open-law` then tell it to sync with all the dependency repos in `openlawlibrary/open-law`. Or I could simply say, create a repo based on `openlawlibrary/open-law` as a template.

We could decouple by having the command actually perform two steps - generate a repository description from the template repo, then apply the repository template as you normally would.

I think the schema you've come up with looks good.

We should use attrs to produce and consume the json.

**Comment by renatav** [comment]
I like that idea. We could have a file called 'YubiKeys' where we would map our custom key ids, which can be Tom, Jason etc. to their public keys. There could then be a command which would remove Jason's key from all roles or just some roles and it would be enough to specify the key id. Based on public keys which are stored in TUF metadata, we could find keys thst no one who is currently on the team has. Is a good idea, but only useful if there aren't any signing keys that were added to delegated repositories not specified in the parent. Not sure if Jason's key was added to openlawlibrary/law
